language: node_js
node_js:
  - 8.0.0
before_script:
  - npm install -g @angular/cli
cache:
  directories:
    - node_modules
services:
 - cassandra
before_script: |-
 cqlsh -e "create keyspace calvin with   replication = {'class':'SimpleStrategy','replication_factor':3}"

 cqlsh -e "create table users(userhandle text,email text primary key ,name text,profilepic text,role text,communities map<text,text>,favouriteCommunities set<text>,lastLogin timestamp)"