FROM mhart/alpine-node

# RUN apk update && \
#     apk add git && \
#     apk add python build-base

RUN mkdir -p /usr/src/

WORKDIR /usr/src/

# RUN npm install -g @angular/cli@latest

COPY package.json .

# RUN npm install --production
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]